### ISSUE TITLE
[BUG] [EMAIL] [MULTI-DOMAIN] [REVERSES DNS]

### ISSUE THREAD

**Issue by lordproducoes** [litespeedtech/cyberpanel#1017]
Hi everyone, what's up?!

I need help setting up an email server on my VPS server. I already have a reverse DNS on my VPS for the main domain dominio1 . com

LOOKING FOR:

> **A mail server other than domain 1, for example mail.domain2 . com**

> **The users enter at dedicated domain mail.dominio2 . com  and can access the email normally - login and passwd.**

The bug/problem is that when I configure a new domain dominio2.net it does not have a reverse DNS (see image -  https://ibb.co/JpmQnHY ).

----

- Domain 1 with e-mail server on the VPS. It already points to the reverse DNS. I already access the manager (Cyberpanel).

- Domain 2 already has a site running Wordpress and there is an SMTP server created for plugin.

Does anyone point me to something?

**Comment by usmannasir** [comment]
rDNS is only for one domain, please see my SMTP guide: https://www.youtube.com/watch?v=k_WriIl_Bo4

**Comment by psycmos** [comment]
The problem is when we add more than one website on Cyberpanel, rDNS only works from one domain, and all others domains with emails will be rejected because rDNS will not reply from the same domain, so it will be classified as spam.

For example CWP panel uses one server for email like srv1.domain.com and all rDNS will be delivery to this sub domain.
So it works for all domains, because was send from srv1.domain.com and reply to the same srv1.domain.com.

That's one big issue of cyberpanel, and all emails will be classified as spam, because the send will be from domain2.com and the rDNS is domain.com.

so in my opinion email server on cyberpanel is not good at all, because not works for more than one domain
