### ISSUE TITLE
[BUG] CSF install is currently disabled

### ISSUE THREAD

**Issue by Pushkraj19** [litespeedtech/cyberpanel#1318]
### Bug Report: CyberPanel 2.3.6 - CSF Installation Issue

**Summary**:  
New installations of CyberPanel version 2.3.6 are not allowing the installation of ConfigServer Security & Firewall (CSF). The error message displayed is "CSF Install is currently disabled." This issue has been reproduced on both Ubuntu 22.04 and 20.04.

**Steps to Reproduce**:
1. Install CyberPanel version 2.3.6 on a fresh installation of Ubuntu 22.04 or Ubuntu 20.04.
2. Attempt to install CSF through the CyberPanel interface.

**Expected Behavior**:  
CSF should install successfully without errors.

**Actual Behavior**:  
The installation fails with the message "CSF Install is currently disabled."

**Environment**:
- **CyberPanel Version**: 2.3.6
- **Operating System**: Ubuntu 22.04 and Ubuntu 20.04

**Additional Information**:
- This issue occurs on fresh installations.
- The same error is encountered on multiple versions of Ubuntu, suggesting it may be a CyberPanel issue rather than an OS-specific problem.

**Possible Workaround**:  
None identified at this time.

**Suggested Priority**: High

**Attachments**: None

Please investigate this issue as it prevents the installation of an essential firewall on new CyberPanel setups.

**Comment by Pushkraj19** [comment]
I tried **CyberPanel Version: 2.3.5**

and when installing it crashes entire panel:

**Internal Error
The server encountered an unexpected condition which prevented it from fulfilling the request.**

**Comment by Pushkraj19** [comment]
anyone taking this seriously? @usmannasir

**Comment by usmannasir** [comment]
Hi,

We've already talked about this here: https://www.facebook.com/groups/cyberpanel/posts/3625527237758898/

We are aware of this issue, and we've been discussing it on Facebook. We've also contacted CSF because we've upgraded our Django version to the latest one, including all the Python packages, but the CSF version is still old. We've tried contacting their support multiple times because we're not getting a proper response from their side. So if you know anyone senior at CSF, please help us get in touch with them because this is their implementation.

I will close this, because we can not do anything in this regard.

**Comment by Pushkraj19** [comment]
Oh. Okay. I didnt know about facebook group. You should mention this somewhere in release notes.
