### ISSUE TITLE
[BUG] CentOS 7 cannot be upgraded to version 2.3.7

### ISSUE THREAD

**Issue by 0xddy** [litespeedtech/cyberpanel#1335]
Python 3.8 has already been installed

python -V    2.7     
python3 -V  3.8

**Screenshots**

![QQ_1728309351992](https://github.com/user-attachments/assets/2e995a6d-7cb4-463f-8dfe-f5d54ef2914a)

![QQ_1728309448136](https://github.com/user-attachments/assets/f62e8c14-2d93-4155-ba45-61d0eeb7c2e1)

**Operating system:**
Centos7.9

**CyberPanel version:**

newer versions ， 2.x.x

**Comment by SaJeTek-Developer** [comment]
What version works with CentOS 7.9?
CentOS 7 is no longer supported by Cyberpanel.

Is it python 3.8 you installed or alt-python38?
The default python3 in CentOS 7.9 is 3.6.8 which Cyberpanel will reference.
i.e. /bin/python3
check `/bin/python3 --version` and see if you get 3.6.8 or 3.8

If your panel is down and inaccessible, then you have 3 options:

1. You can elevate to Almalinux 8/9: https://sajetekengineering.com/blog-article/elevate-centos-7-to-almalinux-9-a-cyberpanel-guide/
2. Rollback to a version compatible with CentOS 7: https://sajetekengineering.com/blog-article/how-to-re-enable-csf-firewall-on-cyberpanel/
3. Reconfigure CentOS to use python 3.8 instead of python 3.6.8 but there may be side effects to this which can be risky if you are running a production server.

**Comment by 0xddy** [comment]
@SaJeTek-Developer      I compiled the official source code of Python3.8, and the installation path is/usr/local/bin/python3.8，Then, ln -s to the new paths/etc/bin/python3 and/etc/python through a soft link. Does using Python 3.6.8, which covers the automatic installation of upgrade scripts, May I ask if this is correct？ pose a high risk?

**Comment by SaJeTek-Developer** [comment]
I'm not sure of the risks of using 3.6.8 but I don't think the only issue is the python version because I have a machine running Almalinux 8 which the default python is 3.6.8 but Cyberpanel is supported and I have been upgraded to v2.3.7.

However: I have experienced the same error as you on another machine running cloud Linux 7 and used my rollback script as to keep the panel up until I elevate to Cloud Linux 8.

It sounds like you have correctly configured the python 3.8 but I did not try that route as I went the route of elevating to Almalinux 9 the machines that were on CentOS 7.

If you wish to continue, you may have some more digging around to try and find a fix.

**Comment by 0xddy** [comment]
@SaJeTek-Developer     
![QQ_1728365298429](https://github.com/user-attachments/assets/346e9086-44e3-46bd-a6d7-f9b3ad8353f0)

How to roll back to the previous version of v2.3.7 if this error occurs during forced updates?

**Comment by SaJeTek-Developer** [comment]
@0xddy I don't think you have to, you have literally reached near completion.
check if you do have a directory `/usr/local/CyberCP/lib` and symlink `/usr/local/CyberCP/lib64` to it

`ln -s /usr/local/CyberCP/lib /usr/local/CyberCP/lib64 `

**Comment by 0xddy** [comment]
@SaJeTek-Developer  
![QQ_1728387217723](https://github.com/user-attachments/assets/04a7edd3-56c3-432c-9f01-0627eb9e8918)

![QQ_1728387297486](https://github.com/user-attachments/assets/5481879d-cd1a-4b41-b488-ba457afe6a7f)

Something even stranger has occurred, and we are ready to replace the Ubuntu system。。

**Comment by SaJeTek-Developer** [comment]
If you are not able to get it working, then try this manual rollback.
This rolls back to a version compatible with CentOS 7.
It's v2.3.5.

https://sajetekengineering.com/blog-article/how-to-re-enable-csf-firewall-on-cyberpanel/

**Comment by 0xddy** [comment]
@SaJeTek-Developer    Thank you for your help, but due to possible confusion in the Python version, it is no longer possible to roll back, and the cyberpanel documentation does not provide detailed instructions on the necessary environment structure, which made me confused when manually solving the problem. Therefore, I decided to migrate the project.

**Comment by 0xddy** [comment]
@SaJeTek-Developer  Hello bro ，Do you know how to change the local database of Cyberpanel to use external MySQL? I couldn't find any database connection configuration related to Cyberpanel

**Comment by SaJeTek-Developer** [comment]
> @SaJeTek-Developer  Hello bro ，Do you know how to change the local database of Cyberpanel to use external MySQL? I couldn't find any database connection configuration related to Cyberpanel

When installing Cyberpanel they ask if to setup remote or local MySQL, if you have already set up the local version, then you can go to the "Databases" menu, then "List Databases", select your database and Manage the Remote access.

I've never had a reason to move away totally from local mysql to fully remote for all websites.

**Comment by 0xddy** [comment]
@SaJeTek-Developer   My application scenario is to use multiple OpenLiteSpeed load balancers, and CyberPanel web only requires a remote database [cyberpanel] to configure multiple CyberPanel web uniformly. This way, after adding a website, there is no need to modify all of them.

**Comment by 0xddy** [comment]
@SaJeTek-Developer  i found this 

![QQ_1728478620267](https://github.com/user-attachments/assets/37c9d491-820d-4de3-9706-7f1cce85ff0d)

The correct remote configuration  file /etc/cyberpanel/mysqlPassword is like this   

```json
{
    "mysqluser":"",
    "mysqlpassword":"",
    "mysqlport":"",
    "mysqlhost":""
}
```
