### ISSUE TITLE
[BUG] All sites are suspended when admin user is suspended

### ISSUE THREAD

**Issue by iqqmuT** [litespeedtech/cyberpanel#1336]
**Describe the bug**
When suspending a user with admin ACL, all sites are suspended.

**To Reproduce**
1. Create a new user with admin ACL
2. Suspend the new user
3. **All** sites are suspended

**Expected behavior**
Not all sites are suspended.

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
2.3

**Additional context**
`UserManager.controlUserState()` gets list of websites to (un)suspend by calling `ACLManager.findAllSites()`. If user is admin, all websites are returned.

https://github.com/usmannasir/cyberpanel/blob/b63d30af650eadad70929f49ac10360f5f2ca454/userManagment/userManager.py#L29

**Comment by usmannasir** [comment]
good to go.

**Comment by master3395** [comment]
Is there an option to suspend just one sub-domain without affecting the entire account? For example, if "wordpress.domain.com" is being abused, it would be helpful to suspend only that sub-domain rather than "domain.com" as a whole.

If a user violates the hosting rules, the goal would be to restrict access to the specific sub-domain, preventing it from being displayed or modified. The user could then be required to contact the host to resolve the issue, without suspending their entire admin account.

Suspending an entire account for issues with one sub-domain seems excessive. It would be more reasonable to suspend only the problematic sub-domain unless the admin specifically chooses to suspend all services.

**Comment by usmannasir** [comment]
You can suspend one single site too from here `/websites/siteState`

or single user too.

**Comment by master3395** [comment]
But not sub-domain, only the whole account or "domain.com", not "sub.domain.com".
Unless you have made each sub-domains as an "website"
