### ISSUE TITLE
CyberPanel Code Review

### ISSUE THREAD

**Issue by Tangol** [litespeedtech/cyberpanel#142]
I've noticed that the CyberPanel project, doesn't use any tools for code analysis.
This is a bad thing, as sometimes bugs and vulnerabilities that are hard to spot, sneak in.

Now here's [CODACY](https://www.codacy.com/), which is free to use for open source projects.
It's an invaluable tool for checking the code quality, that should be added to the project asap.

Also, I've noticed that it's used by many high-profile companies.

Edit: or maybe use [CodeFactor](https://www.codefactor.io/)

**Comment by jordanlambrecht** [comment]
Hey @Tangol. It's been a while since this was submitted. This is, however, a feature request and not an issue with CyberPanel. While I think your idea has merit, the best place to begin a discussion about it would be the [CyberPanel forums](https://forums.cyberpanel.net/categories/feature-request).

Please close this issue to help keep the Issues backlog clean <3
