### ISSUE TITLE
cPanel import does not import cronjobs

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#163]
As the title states any cronjobs that are set in cpanel are not created when the backup is imported into cyberpanel

**Comment by hulst88** [comment]
I experienced the same! .. at least it was good to know it didn't.. haha

**Comment by franciscopaniskaseker** [comment]
Also there is no cyberpanel cli command to create cronjobs.

**Comment by meramsey** [comment]
Looks like the file we need to add cronjob import from is here. Also recommend fixing any crons PHP full binaries paths automatically via RegEx to the cyberpanel lsphp binaries before adding the job. When I get on computer I can dump that information as well from my notes 

Also there is php74 for both cpanel and cyberpanel so that PHP picker will need php74 added when it's updated so sites using those add handlers/versions are properly detected.

File

https://github.com/usmannasir/cyberpanel/blob/stable/plogical/cPanelImporter.py

Backup structure documentation:
https://docs.cpanel.net/knowledge-base/backup/backup-tarball-contents/84/

> /cron
> File — user
> 
> Description — This directory contains a copy of the cPanel account’s crontab.

**Comment by meramsey** [comment]
Here's an example of one of crontab file from backup with stuff generalized

Filename of full backup:
backup-5.4.2019_04-40-55_USERNAME

Filepath to cronbackup file: 
backup-5.4.2019_04-40-55_USERNAME/cron/USERNAME

```
MAILTO="user@example.com"
SHELL="/bin/bash"
* * * * * /bin/sh /home/USERNAME/scripts/whmcs-client-clear-ip.sh >/dev/null 2>&1
0 0 * * 0 /bin/bash /home/USERNAME/scripts/whmcs-register-clean.sh >/dev/null 2>&1
*/5 * * * * /opt/cpanel/ea-php73/root/usr/bin/php -q /home/USERNAME/public_html/my.USERNAME.com/crons/cron.php >/dev/null 2>&1
*/5 * * * * /opt/cpanel/ea-php73/root/usr/bin/php -q /home/USERNAME/public_html/my.USERNAME.com/modules/servers/proxmoxVPS/cron/cron.php  >/dev/null 2>&1
*/5 * * * * /opt/cpanel/ea-php73/root/usr/bin/php -q /home/USERNAME/public_html/my.USERNAME.com/modules/addons/proxmoxAddon/cron/cron.php recoveryList >/dev/null 2>&1
*/5 * * * * /opt/cpanel/ea-php73/root/usr/bin/php -q /home/USERNAME/public_html/my.USERNAME.com/modules/addons/proxmoxAddon/cron/cron.php migrateSync >/dev/null 2>&1
*/5 * * * * /opt/cpanel/ea-php73/root/usr/bin/php -q /home/USERNAME/public_html/my.USERNAME.com/modules/addons/proxmoxAddon/cron/cron.php task >/dev/null 2>&1
```
