### ISSUE TITLE
Backup restoring weird behavior

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#246]
I did a backup of some accounts on server 1 and recovered on server 2.
They are using exactly same environment (centos, cyberpanel version etc).

**What I saw?**
- websites are created on /home/* on server 2 with same users than server 1 (ok!)
- if I click in "list users" I can not see the new users on server 2 **(NOT ok!)**
- if I click in "delete users" I can see the new users (ok!)
- if I click in "list websites" I can not see the new websites recovered on server 2 **(NOT ok!)**
- if I click in "modify user" I can not see the new users on server 2 **(NOT ok!)**
- emails are created on server 2 (ok!)
- forward email rules are not recovered or maybe can not be listed on server 2 **(NOT ok!)**
- if I click in "Delete zone" or "Add/remove record" on DNS section, I can not see the DNS zones of migrated accounts **(NOT ok!)**

I will recreate everything manually due to urgence.

For now I can not rely on cyberpanel backup system.

https://cyberpanel.net/docs/1-backup-restore/ says nothing about that.
https://docs.cyberpanel.net/doku.php?id=cli has no cli command to do that.

**Comment by usmannasir** [comment]
With few points I agree with you, however some need calrification.

- if I click in "list users" I can not see the new users on server 2 (NOT ok!) 

 Agree, right now restored websites are assigned to default admin user, I will take care of this in next releases.

- if I click in "list users" I can not see the new users on server 2 (NOT ok!)
- if I click in "delete users" I can see the new users (ok!)

These above two points I don't know what you are saying, need some clarification. Because no users are created during site restore (except linux users, linux users are needed for PHPSuexec and they are not directly connected to CyberPanel login)

- if I click in "list websites" I can not see the new websites recovered on server 2 (NOT ok!)

You must have received an error message during restore. Recently there was a bug in restore because of additional mail domain creation, which is already fixed.

- if I click in "modify user" I can not see the new users on server 2 (NOT ok!)

Again I am not clear

- forward email rules are not recovered or maybe can not be listed on server 2 (NOT ok!)

Yes forwardings are not included in backup.

- if I click in "Delete zone" or "Add/remove record" on DNS section, I can not see the DNS zones of migrated accounts (NOT ok!)

DNS zones are indeed migrated, but since your backup restore is not success you will not see them, please try to upgrade and retry to restore.

**Comment by franciscopaniskaseker** [comment]
> Agree, right now restored websites are assigned to default admin user, I will take care of this in next releases.

excellent.

> These above two points I don't know what you are saying, need some clarification. Because no users are created during site restore (except linux users, linux users are needed for PHPSuexec and they are not directly connected to CyberPanel login)

At cyberpanel pesperctive, the websites recovered will be assigned to default admin user, but at Linux side, every website is created with own user (linux user). So what I said is... websites at Linux level are created, but no users on cyberpanel perspective... but you explained why: everything go to admin user.

> You must have received an error message during restore. Recently there was a bug in restore because of additional mail domain creation, which is already fixed.

They are created without error. I will update the CP, but is a very fresh installation.

> if I click in "modify user" I can not see the new users on server 2 (NOT ok!)
> Again I am not clear

As you explained, all websites go under admin user... due any CP users created on recover.

> Yes forwardings are not included in backup.

Seems something really simple to do. I think it is important... if I want migrate my CP, I want recover everything as old server. I know you know that.

> DNS zones are indeed migrated, but since your backup restore is not success you will not see them, please try to upgrade and retry to restore.

I will try.

**Comment by usmannasir** [comment]
thanks for the update. I will keep this thread open unless I implement user restore.

**Comment by usmannasir** [comment]
Added https://github.com/usmannasir/cyberpanel/commit/7a7f99f00f2389a9cdd46b658a06fe9b9524887b

Will come when v1.9.5 released.
