### ISSUE TITLE
can't get the size of storage 1 mb issue 

### ISSUE THREAD

**Issue by onexoff** [litespeedtech/cyberpanel#308]
hello i'm running on 2.0 there an issues cyberpanel can't get the size of 
storage disk  it's show 1mb

**Comment by jordanlambrecht** [comment]
Hey @onexoff,

It's a little hard to make sense of this and I'm assuming that's why you haven't received a response yet. If you're still having this problem, can you please provide additional information?

If this is no longer a problem, please close this issue out to help keep the Issues backlog clean.

**Comment by istiak101** [comment]
This is resolved. Can you please close this @usmannasir @whattheserver ?
