### ISSUE TITLE
Provide a way to uninstall

### ISSUE THREAD

**Issue by maicol07** [litespeedtech/cyberpanel#462]
At the moment the only option to remove CyberPanel is reinstall the OS. There should be a better way to do this, like an sh command

**Comment by hennaboy** [comment]
Isnt this the case with most control panels? cpanel, directadmin, plesk I've never seen an uninstall option

**Comment by maicol07** [comment]
Yes, but in the case of installation errors you'll need to reinstall the OS. With this system you could simply uninstall the panel and reinstall it

**Comment by hennaboy** [comment]
Not true. Cyberpanel installs packages like any other software installation. Removing the packages would revert it back to the base os without the need to reinstall.

**Comment by maicol07** [comment]
Ok, but you need to parse installation logs to find what they are. It would be better to provide a list in the docs

**Comment by hennaboy** [comment]
I really see no need for it but if you wish to assist and make a list and contribute.

**Comment by meramsey** [comment]
On nearly all other control panels the only recommended way to "uninstall" is to reinstall. This is normal and not the control panels job to have an uninstall option. We would be happy to add it provided but its doubtful the instructions would be maintained as any updated would potentially break the uninstall instructions due to new file paths configs etc.

If you want some inspiration though see the below link and associated links for how someone tried doing it for cPanel. 
https://forums.cpanel.net/threads/how-to-uninstall-cpanel-and-whm-safely-from-linux.157546/

were going to close this now. if you do want to provide and maintain an uninstall script option feel free to reopen.
