### ISSUE TITLE
/users/listUsers Need a confirmation box before deleting the user account.

### ISSUE THREAD

**Issue by iamprogrammerlk** [litespeedtech/cyberpanel#594]
When I click the Delete button its deletes the user account instantly without confirming the action. this will cause a nightmare when the user clicks it mistakenly.

**Comment by meramsey** [comment]
This appears to be due to the "deleteUserFinal()" called
https://github.com/usmannasir/cyberpanel/blob/stable/userManagment/templates/userManagment/listUsers.html#L62-L64

On the delete page it first hits deleteUser()  and then pops up the are you sure button which then triggers the final deletion.
https://github.com/usmannasir/cyberpanel/blob/stable/userManagment/templates/userManagment/deleteUser.html#L39-L54


Seems like that same approach would be needed in the list user's or a redirect to the dedicated page for it maybe which would handle that better.

@usmannasir any thoughts on this?

**Comment by usmannasir** [comment]
![Screenshot from 2021-04-28 03-44-08](https://user-images.githubusercontent.com/17538454/116321874-5b346d80-a7d4-11eb-89e1-e69dc0485065.png)

Before, deletion it will give prompt like this.
