### ISSUE TITLE
Is Cyberpanel installation borderline malicious?

### ISSUE THREAD

**Issue by murty2** [litespeedtech/cyberpanel#652]
I have serious security concerns and doubts as to whether Cyberpanel install script is malicious. I appreciate the free software and the spirit of sharing the code publicly. It is noble and the actual software itself is good. But it seems the developers know how to ruin a good thing.

- Poor coding. As if it is some sort of literary exercise in bad poetry. Random spaces, obscure error checking, no proper logic skills
- The install scripts assume that you are running on a clean box physically in front of you. Indeed, it will mess up the OS and perform all kinds of things, borderline malicious, worse than other panels
- Attempts to do DNS hijacking and breaking the networking in general. (Question for the genius who coded the install scripts: Is a running systemd-networkd necessary to achieve network connectivity in Linux?)
- Passwords either insecure or in plain. Removes SELinux protection itself; not to mention attempt to add swap and other system level changes without user permission
- Randomly downgrades dependencies. Never mind the security issues in this process

Cyberpanel is a good product and I hope someone forks it and takes it in the right direction. (If my time permits, I might do that myself)

(There is a false belief in the developer community that Windows devs immediately become Sys Admins and Security Admins when they start using Nano editor in Ubuntu. This is is not true. A good dev sticks to what he does best. Alternatively, just releases a Docker or virtual image instead of install scripts)

**Comment by qtwrk** [comment]
Hi,

Thanks for your concerns , first of all,  I am sorry that my very limited knowledge and skills that brought you these concerns.

On the early time of CyberPanel , it comes with certain "prerequisite"  things to do or to check , and it was kind of troublesome to ask users themselves to do these steps so I gathered these stuffs and put into shell script 

I am not a coder and never had chance to systematically studied in coding ,  all I have done was just googling out and put pieces of code together to make it to automate certain steps for users instead of ask them to manually perform it ( some users would have troubling to do so , I have seen a lot of users don't know how to use vi or nano. ) 

-----

should it not to assume a clean OS ?    if you have any method to check if system is "clean" or not , please let me know.

the panel install.py will set resolv.conf to 8.8.8.8 itself , I also need to use different DNS resolver for certain provider like Tencent Cloud and Alibaba Cloud , they have their own internal apt/yum repo server and only resolvable by their own DNS 

I am not sure which password you are referring to  , I only recall that I saved webadmin console pass into a root-read-only file , and this pass can be easily changed by admpass.sh script

if I recall correctly , since very first version of CyberPanel,  it has to disable SELinux before installation, otherwise some feature or component on panel won't work , so I automated that action by script.

I added SWAP because I have seen many users running on small server like 1GB or 2GB RAM, in which mysql is easily and frequently got killed due to OOM so I added SWAP and hoping to ease the case

the sysctl.conf change was attempted to resolve certain issues like max connection limit  , max open file limit ...etc the issues  users have reported , so I thought to apply it automatically so users won't hit same issue again and again.
 
please forgive my short memory , I only recall I downgraded `libgnutls30` on Alibaba Cloud Ubuntu , I had to downgraded it otherwise certain package can not be installed ,  they have kind of special OS image.

if you have any suggestion or solution for these aforementioned issues, please share it out , I will be happy to learn new things and update it.

Best regards,

**Comment by rallisf1** [comment]
I wouldn't call it malicious. Is it bad code? Sure it is. Does it work? Mostly yes and that's good enough for most open source projects.

I believe the core of the problem is that cp still is a 1-man project with a only couple minor bug fixers. There's no design principle used, and when they hit a dead end, either a conflicting library or some security measure like SELinux the solution is to disable it, use an older version etc instead of actually fixing the problem.

In all honesty I have seen paid software that pull worse tricks than cp, still I'd never use cp in an shared / unmanaged hosting environment and no bug fix can change that, cp needs refactoring.

**Comment by master3395** [comment]
> I have serious security concerns and doubts as to whether Cyberpanel install script is malicious. I appreciate the free software and the spirit of sharing the code publicly. It is noble and the actual software itself is good. But it seems the developers know how to ruin a good thing.
> 
> * Poor coding. As if it is some sort of literary exercise in bad poetry. Random spaces, obscure error checking, no proper logic skills
> * The install scripts assume that you are running on a clean box physically in front of you. Indeed, it will mess up the OS and perform all kinds of things, borderline malicious, worse than other panels
> * Attempts to do DNS hijacking and breaking the networking in general. (Question for the genius who coded the install scripts: Is a running systemd-networkd necessary to achieve network connectivity in Linux?)
> * Passwords either insecure or in plain. Removes SELinux protection itself; not to mention attempt to add swap and other system level changes without user permission
> * Randomly downgrades dependencies. Never mind the security issues in this process
> 
> Cyberpanel is a good product and I hope someone forks it and takes it in the right direction. (If my time permits, I might do that myself)
> 
> (There is a false belief in the developer community that Windows devs immediately become Sys Admins and Security Admins when they start using Nano editor in Ubuntu. This is not true. A good dev sticks to what he does best. Alternatively, just releases a Docker or virtual image instead of install scripts)

From the time I installed CyberPanel, I can assure you, that there are security measurements in place for things.
I don't use SELinux, so I can't say much on that end, but there are no passwords stored in plain text, that anyone online can see unless they have the root password.

CyberPanel has 5 sets of plain text for the root admin to see.
/etc/cyberpanel

adminPass (CyberPanel login password))
machineIP (The IP of the cyberpanel install)
mysqlPassword (The password for login into root on MySQL.)
webadmin_password (Original admin password for OLS (ent) )

And
/usr/local/CyberCP/public/rainloop.php (The original admin password for rainloop admin panel, get's changed on CyberPanel upgrade).

But yes, CyberPanel is mostly a 1-man project like rallisf1 said.
People come with suggestions, and some people come with their own help on maintaining and upgrading this panel.

The only major issue that currently is the e-mail setup needing the cloud debugger, in order to resolve.
Other than that V2.1.1 is quite stable.

Not sure where you get the "DNS Hijack" from, because you can set up the DNS anywhere you would like.
You can also use Cloudflare DNS (Making your install more secure).

They do advise that you install CyberPanel on a clean OS, but it's not stopping you from installing it over other panels.
I ran CyberPanel alongside Webadmin, worked fine for a long time.

I see no downgrade in dependencies.
CyberPanel has it's own way of upgrading dependencies, and you can always upgrade dependencies yourself using internal SSH or your own SSH client.

The coding I can't say much, because I've not studied all of the code.
But in all the scripts I've tested with CyberPanel, I don't find many flaws other than the mobile view.
Everyone can pitch in you want to help out.

**Comment by murty2** [comment]
I have no idea that this project is mostly headed by one person. I owe an apology to that person for venting out. It is easy to criticise someone, hard to actually create something functional.

I will look into the code when I get some time.

**Comment by usmannasir** [comment]
Since author questions are answered, I will close this now.
