### ISSUE TITLE
Theme module suggestion

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#668]
Hello, i think it would be a good idea to make the theme of CyberPanel into a module.
That way, it would be easier for the user to change themes they want, not lose themes if they upgrade CyberPanel.
Many people can make their own Themes if they want to make one.

**Comment by istiak101** [comment]
CP is already modular, Django works that way. The issue you are referring is managing CP with Git. It still can be achieved few ways. Loading static files dynamically from Django config is one of them. But it still needs work, so this is more of feature request than an actual issue.

**Comment by istiak101** [comment]
Save config of all available themes and active themes in a json file.
`{
   "active":"theme-one",
   "available":[
      "theme-one",
      "theme-two",
      "theme-three"
   ]
}`
If x theme is active this will load dynamically otherwise default theme will load. Theme installer will add theme name in the json file and change theme function will change the active theme. There would be a default structure and theme variables that still needs to be documented to make more theme developers interested.

**Comment by usmannasir** [comment]
Please keep git for bugs only.
