### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mvalasis** [litespeedtech/cyberpanel#816]
Hi there,

I don't know if the issue is on OLS's side or on CyberPanel's, 
but the problem appears after upgrading from 1.7.14 to 1.7.15 all websites go down with an error "403 too many redirects" or "403 forbidden"

the issue get resolved by logging in on OLS and setting External App Set UID Mode to DocRoot UID
 
I also opened the issue on OLS here: https://github.com/litespeedtech/openlitespeed/issues/303

**Comment by jonathandhn** [comment]
I was typing mine, when I've seen that you post your ticket before mine. To complete with your's I'm pasting the one I was typing. 
Nb : Please correct your's it's 403 "forbidden".

[BUG] Openlitespeed 1.7.15 upgrade on ubuntu 20.04 cause missing External App Set UID Mode on vhosts configs

**Describe the bug**
Users on Cyberpanel 2.1.2 & Ubuntu 20.04 are experiencing 403 errors on their website after Openlitespeed 1.7.15 upgrade from Openlitespeed 1.7.14, External App Set UID Mode config is lost on each vhosts on the server, users need to set it backs and restart openlitespeed. 

**To Reproduce**
Create a vhost prior to  upgrading to Openlitespeed 1.7.15 on Cyberpanel 2.1.2 with Ubuntu 20.04 with a External App Set UID Mode config, then upgrade to Openlitespeed 1.7.15.

**Expected behavior**
All vhosts configs are preserved while migrating between Openlitespeed versions (at least between Openlitespeed minors).

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
2.1.2

**Additional context**
All servers I manage serving Openlitespeed 1.7.14 on ubuntu 20.04 (and oracle linux 8) without cyberpanel, with vhosts prior to Openlitespeed 1.7.15 upgrade have kept and migrated their vhosts configs well, even External App Set UID Mode config. So this seams to be a cyberpanel related Openlitespeed bug.

**Comment by usmannasir** [comment]
```
OLS v1.7.15
-----------------
[Security] Fix a dynamic linking security issue, reported by RACK911.
[Bug Fix] Correct a few minor cache engine issues.
[Bug Fix] "Force Strict Ownership" feature now works as expected. <<<------
[Bug Fix] Address Bubblewrap integration issues. 
[Bug Fix] Address an issue with including the same configuration file multiple times.
[Improvement] New directory auto indexing script.
```

As you can see on third line that issue has been resolved.

**Comment by mvalasis** [comment]
That resolved issue is creating a bug on CyberPanel!

After upgrading OLS to 1.7.15, we had to update all vhosts via OLS and setting External App Set UID Mode to DocRoot UID

Today, I created a new website and it was not working. I had to log in to OLS and and set External App Set UID Mode to DocRoot UID for it to work

Ubuntu 20.04, OLS 1.7.15, CyberPanel 2.1.2
