### ISSUE TITLE
PRs missing from 2.3.1 release

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#864]
Congrats on the 2.3.1 release.

I was surprised that changes I made in the merged #824 PR on the v2.1.2-dev branch were nowhere to be found in [the 2.3.1 version](https://github.com/usmannasir/cyberpanel/blob/v2.3.1/baseTemplate/templates/baseTemplate/index.html#L300).

What's going on here?

**Comment by master3395** [comment]
Can't you re-upload the pr to 2.3.1?

**Comment by Brugman** [comment]
No.

It's not about _my_ PR. But if my merged PR to an older version is missing, then it's likely that a lot more PRs are missing. It's likely that the new version was not properly branched off from the most recent codebase that included all improvements. It's likely a big ass mistake occurred.

**Comment by Tangol** [comment]
This repository is really a mess. It's like the people that manage it either don't know how to use GitHub, or just don't care.
Patches on top of patches, tons of different dev branches etc...

Just look at the releases page: https://github.com/usmannasir/cyberpanel/releases

I don't know why not just have 2 branches: **Main** (stable) and **Dev**.
And for the releases, just do proper ones using GitHub's release/tag system.

My faith ins this project declines day by day...

**Comment by usmannasir** [comment]
Well now I remember that why I've not merged `v2.1.2-dev` into `v2.3.1` right after I merged it, because @nickchomey  was working on fixing some stuff in incremental backups but once I merged `v2.1.2-dev` into `v2.3.1` I can see that it is not completed.

However, I've merged your changes @Brugman and reversed the changes made by @nickchomey 

@Tangol unlike other projects where you can just download the release from Git and make it work, CyberPanel won't work that way.

**Comment by nickchomey** [comment]
Sorry folks, It's considerably more likely that I'm the fool here than Usman. @usmannasir, I suggest you revoke whatever repo permissions you gave me and we be more careful with the status of PRs. 

Though, for anyone who is interested, i've documented very thoroughly my progress and thoughts on Incremental Backups. https://github.com/usmannasir/cyberpanel/issues/831

My recommendation is that the entire mechanism be removed for now - restic is an incomplete solution for it as-is.
